[package]
name = "delta-l"
version = "2.4.1"
authors = ["LFalch <lucas@wasd.dk>"]
edition = "2018"

[features]
nightly = []

[[bin]]
doc = false
name = "delta-l"

[dependencies]
getopts = "0.2"
siphasher = "0.3"
byteorder = "0.5"
